mqtt:
  username: emq
  password: public
  serverURL: tcp://192.168.101.200:1883
  isReconnect: true
  keepAliveInterval: 10
  connectionTimeout: 1000000
  qos: 1

spring:
  profiles:
    path: E:\IdeaProjects\simulate_application
