mqtt:
  username: zq_test
  password: 123456
  serverURL: tcp://192.168.101.200:1883
  isReconnect: true
  keepAliveInterval: 60
  connectionTimeout: 1000000
  qos: 1

spring:
  profiles:
    path: E:\IdeaProjects\simulate_application
